api_request:
  fields:
    config_entry_id: &id001
      selector:
        config_entry:
          integration: unifi_controller
    method:
      required: true
      default: GET
      selector:
        select:
          options:
          - GET
          - POST
          - PUT
          - DELETE
    path:
      required: true
      example: stat/sysinfo
      selector:
        text: {}
    payload:
      selector:
        object: {}
    include_secrets:
      selector:
        boolean: {}
get_objects:
  fields:
    config_entry_id: *id001
    resource: &id002
      required: true
      selector:
        select:
          options:
          - networks
          - wlans
          - firewall_policies
          - firewall_zones
          - firewall_groups
          - trafficrules
          - trafficroutes
          - portforwards
          - routes
          - dns_records
          - port_profiles
          - usergroups
          - qos_rules
          - users
    filter:
      selector:
        text: {}
    refresh:
      selector:
        boolean: {}
    include_secrets:
      selector:
        boolean: {}
update_object:
  fields:
    config_entry_id: *id001
    resource: *id002
    object: &id003
      required: true
      example: Sperre Benjamin Internet
      selector:
        text: {}
    changes:
      required: true
      example: '{"enabled": true}'
      selector:
        object: {}
create_object:
  fields:
    config_entry_id: *id001
    resource: *id002
    data:
      required: true
      selector:
        object: {}
delete_object:
  fields:
    config_entry_id: *id001
    resource: *id002
    object: *id003
set_enabled:
  fields:
    config_entry_id: *id001
    resource: *id002
    object: *id003
    enabled:
      required: true
      selector:
        boolean: {}
refresh:
  fields:
    config_entry_id: *id001
get_logs:
  fields:
    config_entry_id: *id001
    hours:
      selector:
        number:
          min: 1
          max: 720
          unit_of_measurement: h
    limit:
      selector:
        number:
          min: 1
          max: 1000
          mode: box
    category:
      example: SECURITY
      selector:
        text: {}
    filter:
      selector:
        text: {}
ban_ip:
  fields:
    config_entry_id: *id001
    ip: &id004
      required: true
      example: 203.0.113.5
      selector:
        text: {}
    minutes:
      selector:
        number:
          min: 1
          max: 525600
          unit_of_measurement: min
          mode: box
    reason:
      selector:
        text: {}
unban_ip:
  fields:
    config_entry_id: *id001
    ip: *id004
get_bans:
  fields:
    config_entry_id: *id001
regenerate_vpn_key:
  fields:
    config_entry_id: *id001
    vpn:
      required: true
      example: One-Click VPN
      selector:
        text: {}
regenerate_wlan_password:
  fields:
    config_entry_id: *id001
    wlan:
      required: true
      example: guest
      selector:
        text: {}
    length:
      selector:
        number:
          min: 12
          max: 63
          mode: box
    notify:
      selector:
        boolean: {}
block_client:
  fields:
    config_entry_id: *id001
    mac: &id005
      required: true
      example: aa:bb:cc:dd:ee:ff
      selector:
        text: {}
unblock_client:
  fields:
    config_entry_id: *id001
    mac: *id005
reconnect_client:
  fields:
    config_entry_id: *id001
    mac: *id005
forget_client:
  fields:
    config_entry_id: *id001
    mac: *id005
unauthorize_guest:
  fields:
    config_entry_id: *id001
    mac: *id005
restart_device:
  fields:
    config_entry_id: *id001
    mac: *id005
authorize_guest:
  fields:
    config_entry_id: *id001
    mac: *id005
    minutes:
      selector:
        number:
          min: 1
          max: 525600
          unit_of_measurement: min
power_cycle_port:
  fields:
    config_entry_id: *id001
    mac: *id005
    port_idx:
      required: true
      selector:
        number:
          min: 1
          max: 52
          mode: box
set_wlan:
  fields:
    config_entry_id: *id001
    wlan:
      required: true
      example: guest
      selector:
        text: {}
    enabled:
      selector:
        boolean: {}
    passphrase:
      selector:
        text:
          type: password
